import {StyleSheet} from 'react-native';
import colors from '../config/colors';

const styles = StyleSheet.create({
  close: {
    margin: 5,
    position: 'absolute',
    top: 0,
    left: 0,
    width: 30,
    height: 30,
    color: colors.WHITE,
  },
  helpText: {
    color: colors.TORCH_RED,
    fontSize: 15,
    justifyContent: 'space-between',
  },
  subtleLink: {
    color: colors.BLACK,
    fontSize: 17,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: colors.WHITE,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: '10%',
    marginHorizontal: '2%',
  },
  clickable: {
    width: '100%',
    justifyContent: 'center',
    backgroundColor: colors.WHITE,
    marginBottom: 4,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  logo: {
    flex: 1,
    width: '100%',
    resizeMode: 'cover',
    alignSelf: 'center',
    marginBottom: 20,
  },
  form: {
    flex: 1,
    justifyContent: 'center',
    alignSelf: 'center',
    width: '100%',
    backgroundColor: colors.WHITE,
  },
  formFields: {
    flex: 1,
    justifyContent: 'center',
    alignSelf: 'center',
    width: '80%',
    backgroundColor: colors.WHITE,
    paddingTop: 20,
  },
  buttonStyleContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.PURPLE,
    marginVertical: 6,
    paddingVertical: 12,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  tealButtonStyleContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.TEAL,
    marginVertical: 6,
    paddingVertical: 12,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  buttonStyleText: {
    color: colors.WHITE,
    textAlign: 'left',
    height: 20,
    fontWeight: 'bold',
  },
  purpleButtonStyleContainer: {
    width: '30%',
    alignItems: 'center',
    flexDirection: 'row-reverse',
    justifyContent: 'flex-start',
    backgroundColor: colors.PURPLE,
    marginVertical: 6,
    paddingVertical: 12,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  inverseButtonStyleContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.WHITE,
    marginVertical: 6,
    paddingVertical: 12,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.PURPLE,
  },
  inverseButtonStyleText: {
    color: colors.PURPLE,
    textAlign: 'left',
    height: 20,
    fontWeight: 'bold',
  },
  subtitleView: {
    flex: 1,
    flexDirection: 'row',
    paddingLeft: 0,
    paddingTop: 5,
  },
  subtitleSubView: {
    flex: 1,
    flexDirection: 'column',
    paddingLeft: 0,
    paddingTop: 0,
  },
  checkBoxView: {
    flex: 1,
    flexDirection: 'row',
    paddingLeft: 0,
    paddingTop: 5,
  },
  subtitleText: {
    paddingLeft: 0,
    color: colors.REAL_GREY,
  },
  tealSubtitleText: {
    paddingRight: 0,
    color: colors.TEAL,
  },
  animalDetailText: {
    paddingLeft: 0,
    color: colors.DARK_GREY,
    fontSize: 13,
  },
  rightText: {
    textAlign: 'right',
  },
  alertText: {
    paddingLeft: 0,
    color: colors.TORCH_RED,
  },
  rightAlertText: {
    paddingRight: 0,
    color: colors.TORCH_RED,
  },
});

export default styles;
